# -*- coding: utf-8 -*-
"""UI text constants for RoboVision Agent.

All user-facing strings live here so they can be maintained in one place
and swapped at runtime via the _lang key.
"""

from __future__ import annotations

UI_TEXTS: dict[str, dict[str, str | list[str]]] = {
    "zh": {
        "title": "RoboVision Agent",
        "subtitle": "工业视觉预警控制台 | YOLO + RAG + Ollama Gemma",
        "tab_detect": "视觉检测",
        "tab_rag": "RAG 知识问答",
        "tab_logs": "日志与报告",
        "tab_disposal": "事件处置",
        "detect_desc": "上传图片/视频或输入摄像头地址，选择任务，开始检测。",
        "file_label": "上传文件（图片 / 视频）",
        "source_label": "视频源 / 摄像头 / RTSP",
        "source_placeholder": "例如：0（摄像头）| D:/video.mp4 | rtsp://...",
        "task_label": "检测任务",
        "task_choices": ["自动判断", "通用物品检测", "开放词汇检测（图片）", "火灾烟雾预警", "安全帽反光衣工检"],
        "text_label": "文本指令",
        "text_placeholder": "例如：检测图中所有目标 | 开放词汇：叉车、安全帽 | 检查火灾风险",
        "advanced_label": "高级参数",
        "conf_label": "置信阈值",
        "stride_label": "帧间隔",
        "max_frames_label": "最大帧数",
        "run_btn": "\u25b6 开始检测",
        "waiting_text": "*等待输入...*",
        "summary_heading": "\U0001f4ca 检测摘要",
        "annotated_label": "\U0001f5bc 标注结果（图像）",
        "video_label": "\U0001f39e 标注视频",
        "alarm_heading": "\U0001f6a8 报警 / Alarms",
        "json_label": "\U0001f4cb 检测 JSON",
        "log_path_label": "\U0001f4dd 日志路径",
        "rag_desc": "向知识库提问，查询安全规范、处置流程、部署指南等。",
        "rag_question_label": "你的问题",
        "rag_question_placeholder": "例如：检测到烟雾后怎么处理？| 安全帽佩戴规范？| 如何部署到 Jetson？",
        "rag_topk_label": "检索片段数",
        "rag_llm_label": "使用 Ollama Gemma",
        "rag_btn": "\U0001f916 查询 Agent",
        "rag_answer_title": "\U0001f4ac 回答",
        "rag_answer_default": "*你的回答将在此显示...*",
        "rag_details_heading": "\U0001f4cb 详情 / Details",
        "rag_model_label": "模型信息",
        "rag_sources_label": "检索来源",
        "rag_chunks_label": "检索片段",
        "rag_sources_default": "*来源将在此显示...*",
        "rag_chunks_default": "*检索片段将在此显示...*",
        "rag_examples_label": "\U0001f4a1 示例问题",
        "rag_examples_text": "**\U0001f525 火灾安全：** 检测到烟雾后怎么处理？| HIGH/MEDIUM/LOW 报警等级说明 | 火灾报警确认规则\n\n**\U0001faaa PPE 规范：** 安全帽佩戴规范是什么？| 如何分级 PPE 违规？| 危险区域附近人员风险说明\n\n**\U0001f680 部署：** 如何部署到 Jetson？| ONNX 导出注意事项 | 推荐硬件\n\n**\U0001f4cb 项目：** RoboVision Agent 能做什么？| 如何使用巡检报告？| 有哪些可用模型？",
        "logs_desc": "查询日志、报告、报警历史，或通过 Agent 自动生成报告。",
        "log_query_label": "日志查询",
        "log_query_placeholder": "例如：最近报警 | 巡检报告 | 火灾日志",
        "log_query_btn": "\U0001f916 查询",
        "log_result_heading": "\U0001f4ca 结果 / Results",
        "log_result_default": "*等待查询...*",
        "log_alarm_heading": "\U0001f6a8 报警截图",
        "log_report_label": "\U0001f4dd 报告路径",
        "log_stats_heading": "\U0001f4f1 统计概览",
        "detail_label": "运行详情（JSON / 日志 / Agent 轨迹）",
        "trace_label": "Agent 执行轨迹",
        "clear_label": "清空",
        "footer": "RoboVision Agent v1.0 \u00b7 YOLO + RAG + Ollama Gemma \u00b7 工业视觉预警控制台",
    },
    "en": {
        "title": "RoboVision Agent",
        "subtitle": "Industrial Vision Alert Console | YOLO + RAG + Ollama Gemma",
        "tab_detect": "Vision Detection",
        "tab_rag": "RAG Knowledge Q&A",
        "tab_logs": "Logs & Reports",
        "tab_disposal": "Event Disposal",
        "detect_desc": "Upload images/videos or enter a camera source, select a task, and start detection.",
        "file_label": "Upload File (Image / Video)",
        "source_label": "Video Source / Camera / RTSP",
        "source_placeholder": "e.g.: 0 (camera) | D:/video.mp4 | rtsp://...",
        "task_label": "Detection Task",
        "task_choices": ["Auto Detect", "General Object Detection", "Open Vocabulary (Image)", "Fire & Smoke Warning", "PPE Safety Helmet & Reflective Vest Check"],
        "text_label": "Text Instruction",
        "text_placeholder": "e.g.: Detect all targets | Open vocabulary: forklift, helmet | Check fire risk",
        "advanced_label": "Advanced Parameters",
        "conf_label": "Confidence Threshold",
        "stride_label": "Frame Stride",
        "max_frames_label": "Max Frames",
        "run_btn": "\u25b6 Start Detection",
        "waiting_text": "*Waiting for input...*",
        "summary_heading": "\U0001f4ca Detection Summary",
        "annotated_label": "\U0001f5bc Annotated Result",
        "video_label": "\U0001f39e Annotated Video",
        "alarm_heading": "\U0001f6a8 Alarms",
        "json_label": "\U0001f4cb Detection JSON",
        "log_path_label": "\U0001f4dd Log Path",
        "rag_desc": "Ask the knowledge base about safety regulations, disposal procedures, deployment guides, etc.",
        "rag_question_label": "Your Question",
        "rag_question_placeholder": "e.g.: How to handle detected smoke? | PPE wearing regulations? | How to deploy to Jetson?",
        "rag_topk_label": "Retrieval Top-K",
        "rag_llm_label": "Use Ollama Gemma",
        "rag_btn": "\U0001f916 Ask Agent",
        "rag_answer_title": "\U0001f4ac Answer",
        "rag_answer_default": "*Your answer will appear here...*",
        "rag_details_heading": "\U0001f4cb Details",
        "rag_model_label": "Model Info",
        "rag_sources_label": "Retrieval Sources",
        "rag_chunks_label": "Retrieved Chunks",
        "rag_sources_default": "*Sources will appear here...*",
        "rag_chunks_default": "*Retrieved chunks will appear here...*",
        "rag_examples_label": "\U0001f4a1 Example Questions",
        "rag_examples_text": "**\U0001f525 Fire Safety:** How to handle detected smoke? | HIGH/MEDIUM/LOW alarm levels explained | Fire alarm confirmation rules\n\n**\U0001faaa PPE Regulations:** What are the helmet wearing regulations? | How to grade PPE violations? | Personnel risk near hazardous areas\n\n**\U0001f680 Deployment:** How to deploy to Jetson? | ONNX export notes | Recommended hardware\n\n**\U0001f4cb Project:** What can RoboVision Agent do? | How to use inspection reports? | Available models?",
        "logs_desc": "Query logs, reports, alarm history, or auto-generate reports via Agent.",
        "log_query_label": "Log Query",
        "log_query_placeholder": "e.g.: Recent alarms | Inspection report | Fire log",
        "log_query_btn": "\U0001f916 Query",
        "log_result_heading": "\U0001f4ca Results",
        "log_result_default": "*Waiting for query...*",
        "log_alarm_heading": "\U0001f6a8 Alarm Screenshots",
        "log_report_label": "\U0001f4dd Report Path",
        "log_stats_heading": "\U0001f4f1 Statistics",
        "detail_label": "Run Details (JSON / Logs / Agent Trace)",
        "trace_label": "Agent Trace",
        "clear_label": "Clear",
        "footer": "RoboVision Agent v1.0 \u00b7 YOLO + RAG + Ollama Gemma \u00b7 Industrial Vision Alert Console",
    },
}
